第一课作业
Guigulive/Team-I pull request #5
Opened 2018-03-13 11:12 UTC by Mochangxing

2018-03-14 00:16 UTC, topmorphs requested changes

2018-03-14 00:16 UTC, topmorphs commented on Lesson-1/assignment/payroll.sol
> +
lastPayday should be updated to now

2018-03-14 00:16 UTC, topmorphs commented on Lesson-1/assignment/payroll.sol
> +        }
LastPayDay should be updated

2018-03-21 13:03 UTC, Mochangxing commented
82_莫昌星_第三次作业

2018-03-21 18:16 UTC, closed without merging