90_徐蕴博_第一课作业
Guigulive/Team-I pull request #8
Opened 2018-03-14 12:04 UTC by xuyunbo

2018-03-15 17:25 UTC, topmorphs commented on Lesson-1/assignment/yours.sol
> +    function PayrallHomeWork() {
Payroll instead of Payrall

2018-03-17 13:17 UTC, xuyunbo commented
90_徐蕴博_第二课作业

2018-03-17 13:26 UTC, xuyunbo commented
改了第一课作业的单词拼写错误

2018-03-17 13:32 UTC, xuyunbo reviewed
谢谢大哥

2018-03-19 05:49 UTC, topmorphs requested changes

2018-03-19 05:49 UTC, topmorphs commented on Lesson-1/assignment/yours.sol
> +    function addfurd() payable returns (uint) {
addFund instead addFurd

2018-03-19 05:49 UTC, topmorphs commented on Lesson-2/assignment/yours_optimized.sol
> +        len--;
use employees.length -= 1;

2018-03-21 18:17 UTC, merged